---
apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: aci-ran-volante-cars-lab
  namespace: assisted-installer
  annotations:
    agent-install.openshift.io/install-config-overrides: '{"networking":{"networkType":"OVNKubernetes"}}'
spec:
  apiVIP: updateMe
  ingressVIP: updateMe
  clusterDeploymentRef:
    name: aci-ran-volante-cars-lab
  imageSetRef:
    name: openshift-v4.8.19
  networking:
    clusterNetwork:
      - cidr: "10.128.0.0/14"
        hostPrefix: 23
    serviceNetwork:
      - "172.30.0.0/16"
  provisionRequirements:
    controlPlaneAgents: 3
    workerAgents: 2
  sshPublicKey: 'updateMe'
