---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-super1-volante-cars-lab
  namespace: assisted-installer
  labels:
    cluster-name: volante-nmstate
spec:
  config:
    interfaces:
      - name: enp1s0
        type: ethernet
        state: up
        macAddress: changeMe
        ipv4:
          address:
          - ip: changeMe
            prefix-length: 24
          enabled: true
    dns-resolver:
      config:
        server:
          - 10.40.0.100
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: changeMe
          next-hop-interface: enp1s0
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-super2-volante-cars-lab
  namespace: assisted-installer
  labels:
    cluster-name: volante-nmstate
spec:
  config:
    interfaces:
      - name: enp1s0
        type: ethernet
        state: up
        macAddress: changeMe
        ipv4:
          address:
          - ip: changeMe
            prefix-length: 24
          enabled: true
    dns-resolver:
      config:
        server:
          - 10.40.0.100
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: changeMe
          next-hop-interface: enp1s0
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-super3-volante-cars-lab
  namespace: assisted-installer
  labels:
    cluster-name: volante-nmstate
spec:
  config:
    interfaces:
      - name: enp1s0
        type: ethernet
        state: up
        macAddress: changeMe
        ipv4:
          address:
          - ip: changeMe
            prefix-length: 24
          enabled: true
    dns-resolver:
      config:
        server:
          - 10.40.0.100
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: changeMe
          next-hop-interface: enp1s0
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-worker1-volante-cars-lab
  namespace: assisted-installer
  labels:
    cluster-name: volante-nmstate
spec:
  config:
    interfaces:
      - name: enp1s0
        type: ethernet
        state: up
        macAddress: changeMe
        ipv4:
          address:
          - ip: changeMe
            prefix-length: 24
          enabled: true
    dns-resolver:
      config:
        server:
          - 10.40.0.100
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: changeMe
          next-hop-interface: enp1s0
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-worker2-volante-cars-lab
  namespace: assisted-installer
  labels:
    cluster-name: volante-nmstate
spec:
  config:
    interfaces:
      - name: enp1s0
        type: ethernet
        state: up
        macAddress: changeMe
        ipv4:
          address:
          - ip: changeMe
            prefix-length: 24
          enabled: true
    dns-resolver:
      config:
        server:
          - 10.40.0.100
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: changeMe
          next-hop-interface: enp1s0
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-mgmt3-volante-cars-lab
  namespace: assisted-installer
  labels:
    cluster-name: volante-nmstate
spec:
  config:
    interfaces:
      - name: bond0
        type: bond
        state: up
        ipv4:
          enabled: true
          address:
            - ip: 172.17.0.103
              prefix-length: 24
          dhcp: false
        link-aggregation:
          mode: active-backup
          options:
            miimon: '150'
            primary: ens7f0
          slaves:
          - ens7f0
          - ens7f1
      - name: ens1f0
        type: ethernet
        state: down
      - name: ens1f1
        type: ethernet
        state: down
    dns-resolver:
      config:
        server:
          - 10.40.0.100
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 172.17.0.1
          next-hop-interface: bond0
  interfaces:
    - name: ens1f0
      macAddress: 40:A6:B7:3D:D7:50
    - name: ens1f1
      macAddress: 40:A6:B7:3D:D7:51
    - name: ens7f0
      macAddress: 40:A6:B7:3D:D4:F0
    - name: ens7f1
      macAddress: 40:A6:B7:3D:D4:F1
