---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: open-cluster-management
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-local-storage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-cluster-management:subscription-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:subscription-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: kube:admin
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:admin
---
apiVersion: config.openshift.io/v1
kind: Scheduler
metadata:
  name: cluster
spec:
  mastersSchedulable: true
---
apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: max-pods-500
spec:
  kubeletConfig:
    maxPods: 500
    podsPerCore: 0
  machineConfigPoolSelector:
    matchLabels:
      custom-kubelet: max-pods-500
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 50-worker-fix-ipi-rwn
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - contents:
          source: data:,
          verification: {}
        filesystem: root
        mode: 420
        path: /etc/kubernetes/manifests/keepalived.yaml
      - contents:
          source: data:,
          verification: {}
        filesystem: root
        mode: 420
        path: /etc/kubernetes/manifests/mdns-publisher.yaml
      - contents:
          source: data:,
          verification: {}
        filesystem: root
        mode: 420
        path: /etc/kubernetes/manifests/coredns.yaml
    systemd:
      units:
      - contents: |
          [Unit]
          Description=Writes IP address configuration so that kubelet and crio services select a valid node IP
          Wants=network-online.target
          After=network-online.target ignition-firstboot-complete.service
          Before=kubelet.service crio.service
          [Service]
          Type=oneshot
          ExecStart=/bin/bash -c "exit 0 "
          [Install]
          WantedBy=multi-user.target
        enabled: true
        name: nodeip-configuration.service
---
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: multiclusterhub
  namespace: open-cluster-management
spec: {}
---
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  labels:
    telco-gitops/rwn: telco-gitops
  name: default
  namespace: openshift-ingress-operator
spec:
  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/master: ""
  replicas: 3
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: open-cluster-management
  namespace: open-cluster-management
spec:
  targetNamespaces:
  - open-cluster-management
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: acm-operator-subscription
  namespace: open-cluster-management
spec:
  channel: release-2.5
  installPlanApproval: Automatic
  name: advanced-cluster-management
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
  namespace: openshift-operators
spec:
  channel: latest
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: openshift-pipelines-operator-rh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: hive.openshift.io/v1
kind: HiveConfig
metadata:
  name: hive
spec:
  featureGates:
    custom:
      enabled:
      - AlphaAgentInstallStrategy
    featureSet: Custom
  logLevel: debug
  targetNamespace: hive
---
apiVersion: metal3.io/v1alpha1
kind: Provisioning
metadata:
  name: provisioning-configuration
spec:
  disableVirtualMediaTLS: true      
  provisioningNetwork: Disabled
  #provisioningOSDownloadURL: 'https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases/rhcos-4.9/49.84.202110081407-0/x86_64/rhcos-49.84.202110081407-0-openstack.x86_64.qcow2.gz?sha256=bbbb9243f084fc330a2c95e0bf33708d68e17628f48086eac574dcb96d35df9e'
  watchAllNamespaces: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: assisted-service-config
  namespace: multicluster-engine
data:
  LOG_LEVEL: "debug"
  SUPPORT_L2: "false"
  DISABLED_HOST_VALIDATIONS: "belongs-to-machine-cidr,belongs-to-majority-group"
  #PUBLIC_CONTAINER_REGISTRIES: "quay.io,registry.svc.ci.openshift.org,registry.redhat.io"
  ISO_IMAGE_TYPE: "full-iso"
  #ASSISTED_SERVICE_IMAGE: registry.redhat.io/rhacm2/agent-service-rhel8@sha256:2e3f3795de17f08c30dd81e90aeb86998a572b8953368b7f181d34a445a84eb2
  #SERVICE_IMAGE: registry.redhat.io/rhacm2/agent-service-rhel8@sha256:2e3f3795de17f08c30dd81e90aeb86998a572b8953368b7f181d34a445a84eb2
  #SELF_IMAGE: registry.redhat.io/rhacm2/agent-service-rhel8@sha256:2e3f3795de17f08c30dd81e90aeb86998a572b8953368b7f181d34a445a84eb2
  #IMAGE_SERVICE_IMAGE: registry.redhat.io/rhacm2/assisted-image-service-rhel8@sha256:9768e9a73324561133f159ca6a2397e6a31de28abdc47be5b5fae444aeab20e3
  #AGENT_DOCKER_IMAGE: registry.redhat.io/rhacm2/assisted-installer-agent-rhel8@sha256:f53598df253ef2762d1f0b74bd4bcb0735379d6b13fb88ecf8acac5946bcbc53
  #CONTROLLER_IMAGE: registry.redhat.io/rhacm2/assisted-installer-reporter-rhel8@sha256:ee14648f60f46face43da4a7b26a1e7911fe0eae9a3b8ade5db476b22e085fca
  #INSTALLER_IMAGE: registry.redhat.io/rhacm2/assisted-installer-rhel8@sha256:c809bb9d532788163391d7183fccda26b020270865f34cf652ffe4419c4ae6a6
---
apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
  name: agent
  annotations:
    unsupported.agent-install.openshift.io/assisted-service-configmap: 'assisted-service-config'
spec:
  databaseStorage:
    #bug, leave default class for now
    #storageClassName: lso-blockclass
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
  filesystemStorage:
    #bug, leave default class for now
    #storageClassName: lso-filesystemclass
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 40Gi
  imageStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
  #mirrorRegistryRef:
    # for disconnected installs
    #name: "disconnected-mirror-config"
  osImages:
    #- openshiftVersion: "4.6"
    #  version: "46.82.202012051820-0"
    #  url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.8/rhcos-4.6.8-x86_64-live.x86_64.iso"
    #  rootFSUrl: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.8/rhcos-live-rootfs.x86_64.img"
    - openshiftVersion: "4.8"
      cpuArchitecture: x86_64
      version: "48.84.202107202156-0"
      url: "http://10.40.0.100/ztp-dave/rhcos-4.8.14-x86_64-live.x86_64.iso"
      rootFSUrl: "http://10.40.0.100/ztp-dave/rhcos-4.8.14-x86_64-live-rootfs.x86_64.img"
    - openshiftVersion: "4.9"
      cpuArchitecture: x86_64
      version: "49.84.202206171736-0"
      url: "http://10.40.0.100/ztp-dave/rhcos-4.9.40-x86_64-live.x86_64.iso"
      rootFSUrl: "http://10.40.0.100/ztp-dave/rhcos-4.9.40-x86_64-live-rootfs.x86_64.img"
    - openshiftVersion: "4.10"
      cpuArchitecture: x86_64
      version: "410.84.202205191234-0"
      url: "http://10.40.0.100/ztp-dave/rhcos-4.10.16-x86_64-live.x86_64.iso"
      rootFSUrl: "http://10.40.0.100/ztp-dave/rhcos-4.10.16-x86_64-live-rootfs.x86_64.img"
    - openshiftVersion: "4.11"
      cpuArchitecture: x86_64
      version: "11.86.202207090519-0"
      url: "http://10.40.0.100/ztp-dave/rhcos-4.11.0-rc.2-x86_64-live.x86_64.iso"
      rootFSUrl: "http://10.40.0.100/ztp-dave/rhcos-4.11.0-rc.2-x86_64-live-rootfs.x86_64.img"
