---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
 name: volt-cars-lab
 namespace: openshift-gitops
spec:
  generators:
    - git:
        directories:
          - path: rhocp-clusters/volt.cars.lab/config-*
        repoURL: 'https://github.com/novacain1/carslab-public.git'
        revision: HEAD
  template:
    metadata:
      name: 'volt-{{path.basename}}'
      namespace: openshift-gitops
    spec:
      destination:
        namespace: openshift-gitops
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        path: '{{path}}'
        repoURL: 'https://github.com/novacain1/carslab-public.git'
        targetRevision: HEAD
