---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: openshift-v4.8.31
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:4.8.31-x86_64
---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: openshift-v4.9.21
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:4.9.21-x86_64
---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: openshift-v4.10.0-rc.2
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:4.10.0-rc.2-x86_64
