---
apiVersion: v1
kind: Secret
metadata:
  name: bmc-mgmt1-skylark-cars-lab
  namespace: skylark-cars-lab
data:
  username: cm9vdA==
  password: YWx0aW9zdGFyMTIz
type: Opaque
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: mgmt1-skylark-cars-lab
  namespace: skylark-cars-lab
  labels:
    infraenvs.agent-install.openshift.io: "infraenv-skylark-cars-lab"
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "mgmt1"
    bmac.agent-install.openshift.io/role: worker
    bmac.agent-install.openshift.io/installer-args: '["--copy-network"]'
    bmac.agent-install.openshift.io/ignition-config-overrides: '{"ignition":{"version":"3.2.0"},"storage":{"disks":[{"device":"/dev/sdb","partitions":[{"label":"root","number":4,"resize":true,"sizeMiB":204800},{"label":"lso_10G_1","sizeMiB":10240},{"label":"lso_10G_2","sizeMiB":10240},{"label":"lso_10G_3","sizeMiB":10240}],"wipeTable":false}]}}'
spec:
  online: true
  bootMACAddress: 40:A6:B7:3D:D7:30
  automatedCleaningMode: disabled
  rootDeviceHints:
    deviceName: /dev/sdb
  bmc:
    address: idrac-virtualmedia://172.28.11.36/redfish/v1/Systems/System.Embedded.1
    credentialsName: bmc-mgmt1-skylark-cars-lab
    disableCertificateVerification: True
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-mgmt1-skylark-cars-lab
  namespace: skylark-cars-lab
  labels:
    cluster-name: skylark-nmstate
spec:
  config:
    interfaces:
      - name: bond0
        type: bond
        state: up
        ipv4:
          enabled: true
          address:
            - ip: 172.17.0.101
              prefix-length: 24
          dhcp: false
        ipv6:
          enabled: true
          address:
          - ip: fd00:6:6:2060::101
            prefix-length: 64
          autoconf: false
          dhcp: false
        link-aggregation:
          mode: active-backup
          options:
            miimon: '100'
            primary: ens7f0
          port:
          - ens7f0
          - ens7f1
      - name: ens1f0
        type: ethernet
        state: down
      - name: ens1f1
        type: ethernet
        state: down
    dns-resolver:
      config:
        server:
        - 10.40.0.100
        - fd00:6:6:11::52
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 172.17.0.1
          next-hop-interface: bond0
        - destination: ::/0
          next-hop-address: fd00:6:6:2060::1
          next-hop-interface: bond0
  interfaces:
    - name: ens1f0
      macAddress: 40:a6:b7:3d:c5:30
    - name: ens1f1
      macAddress: 40:a6:b7:3d:c5:31
    - name: ens7f0
      macAddress: 40:a6:b7:3d:d7:30
    - name: ens7f1
      macAddress: 40:a6:b7:3d:d7:31
