---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  #- 00-namespace.yaml
  #- 01-pullsecret.yaml
  - 02-aci.yaml
  - 03-clusterdeployment.yaml
  - 04-klusterletaddon.yaml
  - 05-managedcluster.yaml
  - 06-infraenv-skylark-cars-lab.yaml
  - 07-nmstate-skylark-cars-lab-cplane.yaml
  - 08-bmh-skylark-cars-lab-cplane.yaml
